### ISSUE TITLE
Unable to connect to devnet wallet

### ISSUE THREAD

**Issue by ericstran** [sol-surfer-nft/sol-surfer-ui#15]
These are the errors I got from trying to connect on these wallets:

Sollet: Unhandled Rejection (Error): failed to get info about account oAi5miM72dpWeMfqEbBbB7nciuds5NG37NS5VANpY4R: TypeError: Failed to fetch

solong: Unhandled Rejection (Error): failed to get info about account 11111111111111111111111111111111: TypeError: Failed to fetch

solflare: Unhandled Rejection (Error): failed to get info about account CXhG3vEDHjJUShoZijKfTid8FeVmfgGDDgFPpEuZrsMU: TypeError: Failed to fetch

ledger: Unhandled Rejection (Error): failed to get info about account 11111111111111111111111111111111: TypeError: Failed to fetch

phantom: Unhandled Rejection (Error): failed to get info about account 11111111111111111111111111111111: TypeError: Failed to fetch

Possible Fixes:
comment out the option for devnet and testnet (serum dex doesn't have them as options)

**Comment by nstranquist** [comment]
When the account says "111..." you are not using a valid / recognized account.
When it knows the account address but still cannot connect, that is because you are not running the devnet on your local machine correctly. There's some more information about this on solana's documentation for connecting to devnet.
